name       : gdal
version    : 3.4.2
release    : 28
source     :
    - https://github.com/OSGeo/gdal/releases/download/v3.4.2/gdal-3.4.2.tar.gz : 7edef6de47c67da806b74eb8d3a20550933392a295c707682ea21b72123e34ce
homepage   : https://www.gdal.org/
license    : MIT
component  : programming
summary    : GDAL - Geospatial Data Abstraction Library
description: |
    GDAL is a translator library for raster and vector geospatial data formats.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(cfitsio)
    - pkgconfig(geos)
    - pkgconfig(hdf5)
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - pkgconfig(libheif)
    - pkgconfig(liblzma)
    - pkgconfig(libmariadb)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpq)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(libzstd)
    - pkgconfig(netcdf)
    - pkgconfig(odbc)
    - pkgconfig(poppler)
    - pkgconfig(proj)
    - pkgconfig(python3)
    - pkgconfig(qhull_r)
    - pkgconfig(spatialite)
    - pkgconfig(sqlite3)
    - pkgconfig(xerces-c)
    - giflib-devel
    - libgeotiff-devel
    - numpy
    - swig
rundeps    :
    - numpy
setup      : |
    %reconfigure \
        --with-cpp14 \
        --with-bash-completion=/usr/share/bash-completion/completions \
        --with-liblzma \
        --with-mysql \
        --with-poppler \
        --with-python3 \
        --with-qhull \
        --with-spatialite \
        --with-zstd
build      : |
    %make

    pushd swig/python
        python3 setup.py build
    popd
install    : |
    # do it first so executables are Python 2
    pushd swig/python
        python3 setup.py install --skip-build --root="%installroot%"
    popd

    %make_install
    rm -f $installdir/usr/lib*/*.a
