name       : gdal
version    : 2.1.1
release    : 1
source     :
    - http://download.osgeo.org/gdal/2.1.1/gdal-2.1.1.tar.xz : 87ce516ce757ad1edf1e21f007fbe232ed2e932af422e9893f40199711c41f92
license    : MIT
component  : programming
summary    : GDAL - Geospatial Data Abstraction Library
description: |
    GDAL is a translator library for raster and vector geospatial data formats
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(sqlite3)
    - pkgconfig(xerces-c)
    - geos
    - giflib-devel
    - hdf5-devel
    - jasper-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static \
               --datadir=/usr/share/gdal \
               --with-liblzma=yes
build      : |
    %make
install    : |
    %make_install
    rm -f /usr/lib64/libgdal.a
    install -d $installdir/usr/share/bash-completion
    mv $installdir/usr/etc/bash_completion.d/gdal-bash-completion.sh $installdir/usr/share/bash-completion/gdal
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal-config
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_contour
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_grid
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_rasterize
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_translate
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaladdo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalbuildvrt
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaldem
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalenhance
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdallocationinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalmanage
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalserver
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalsrsinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaltindex
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaltransform
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalwarp
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/nearblack
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogr2ogr
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrlineref
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrtindex
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/testepsg
    rm -Rf $installdir/usr/etc