name       : gdal
version    : 3.3.1
release    : 20
source     :
    - https://github.com/OSGeo/gdal/releases/download/v3.3.1/gdal-3.3.1.tar.gz : 6c3c2422d129a9fef030d6aaa5bd3dd45ee798808953099313ffd36ab2945055
homepage   : https://www.gdal.org/
license    : MIT
component  : programming
summary    : GDAL - Geospatial Data Abstraction Library
description: |
    GDAL is a translator library for raster and vector geospatial data formats
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libtiff-4)
    - pkgconfig(libopenjp2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(proj)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
    - pkgconfig(xerces-c)
    - geos
    - giflib-devel
    - hdf5-devel
    - numpy
rundeps    :
    - numpy
setup      : |
    %configure --datadir=/usr/share/gdal \
               --with-geos \
               --with-liblzma \
               --with-png \
               --with-webp \
build      : |
    %make

    pushd swig/python
        python3 setup.py build
    popd
install    : |
    pushd swig/python
        python3 setup.py install --skip-build --root="%installroot%"
    popd

    %make_install
    rm -f /usr/lib64/libgdal.a

    install -d $installdir/usr/share/bash-completion
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal-config
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_contour
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_grid
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_rasterize
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_translate
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaladdo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalbuildvrt
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaldem
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalenhance
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdallocationinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalmanage
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalserver
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalsrsinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaltindex
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaltransform
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalwarp
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/nearblack
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogr2ogr
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrlineref
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrtindex
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/testepsg
    rm -Rf $installdir/usr/etc
