name       : gdal
version    : 2.2.4
release    : 11
source     :
    - https://download.osgeo.org/gdal/2.2.4/gdal-2.2.4.tar.xz : 441eb1d1acb35238ca43a1a0a649493fc91fdcbab231d0747e9d462eea192278
homepage   : http://www.gdal.org/
license    : MIT
component  : programming
summary    : GDAL - Geospatial Data Abstraction Library
description: |
    GDAL is a translator library for raster and vector geospatial data formats
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
    - pkgconfig(xerces-c)
    - geos
    - giflib-devel
    - hdf5-devel
    - numpy
rundeps    :
    - numpy
setup      : |
    %configure --datadir=/usr/share/gdal \
               --with-geos \
               --with-liblzma \
               --with-png \
               --with-python \
               --with-webp \
               --with-xerces-c
build      : |
    %make

    pushd swig/python
        python3 setup.py build
    popd
install    : |
    # do it first so executables are Python 2
    pushd swig/python
        python3 setup.py install --skip-build --root="%installroot%"
    popd

    %make_install
    rm -f /usr/lib64/libgdal.a

    install -d $installdir/usr/share/bash-completion
    mv $installdir/usr/etc/bash_completion.d/gdal-bash-completion.sh $installdir/usr/share/bash-completion/gdal
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal-config
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_contour
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_grid
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_rasterize
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdal_translate
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaladdo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalbuildvrt
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaldem
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalenhance
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdallocationinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalmanage
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalserver
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalsrsinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaltindex
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdaltransform
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/gdalwarp
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/nearblack
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogr2ogr
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrinfo
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrlineref
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/ogrtindex
    ln -s /usr/share/bash-completion/gdal $installdir/usr/share/bash-completion/testepsg
    rm -Rf $installdir/usr/etc
